const FakeData = [{
    "id": "1",
    "image": "https://i.ibb.co/PcCfFc0/Rectangle-396.png",
    "apartment_name": "Washington Avenue",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 194,
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
},
{
    "id": "2",
    "image": "https://i.ibb.co/ggm7rmH/Rectangle-398.png",
    "apartment_name": "Family Apartment Three",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 356,
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
},
{
    "id": "3",
    "image": "https://i.ibb.co/dtNL8dP/Rectangle-403.png",
    "apartment_name": "Gorgeous house",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 256,
    "rent_month": "$550 (negotiable)",
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
},
{
    "id": "4",
    "image": "https://i.ibb.co/9ytgNnv/Rectangle-404.png",
    "apartment_name": "Luxury villa ",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 345,
    "rent_month": "$550 (negotiable)",
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
},
{
    "id": "5",
    "image": "https://i.ibb.co/vmtp8xq/Rectangle-405.png",
    "apartment_name": "Epic Huda Palacio",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 536,
    "rent_month": "$550 (negotiable)",
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
},
{
    "id": "6",
    "image": "https://i.ibb.co/y4xDQN4/Rectangle-394.png",
    "apartment_name": "Washington Avenue",
    "address": "Nasirabad H/S, Chattogram",
    "no_bedrooms": 2,
    "no_bathroom": 3,
    "price": 283,
    "rent_month": "$550 (negotiable)",
    "service_charge" : "8,000/= Tk per month, subject to change",
    "security_deposit" : "3 month’s rent",
    "flat_release_policy" : "3 months earlier notice required",
    "property_details": "Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor :  A5 (5th Floor) (6 storied Building ) (South Facing Unit), Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
}];

export default FakeData;